version: "3.5"

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=hotline
    ports:
      - "5432:5432"
networks:
  default:
    driver: bridge
