-- MySQL Script generated by MySQL Workbench
-- Mon Oct  9 10:57:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop` DEFAULT CHARACTER SET utf8 ;
USE `shop` ;

-- -----------------------------------------------------
-- Table `shop`.`price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`price` (
  `firmId` INT NOT NULL,
  `date` DATETIME NULL,
  `firmName` VARCHAR(225) NULL,
  `rate` FLOAT NULL,
  PRIMARY KEY (`firmId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`category` (
  `category_Id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(225) NULL,
  `firm_id` INT NULL,
  PRIMARY KEY (`category_Id`),
  UNIQUE INDEX `category_Id_UNIQUE` (`category_Id` ASC) VISIBLE,
  INDEX `fid_idx` (`firm_id` ASC) VISIBLE,
  CONSTRAINT `CtFid`
    FOREIGN KEY (`firm_id`)
    REFERENCES `shop`.`price` (`firmId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`items` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `category_Id` INT NULL,
  `vendor` VARCHAR(225) NULL,
  `name` VARCHAR(225) NULL,
  `description` TEXT(10000) NULL,
  `url` VARCHAR(225) NULL,
  `priceRUAH` FLOAT NULL,
  `firm_id` INT NULL,
  PRIMARY KEY (`item_id`),
  UNIQUE INDEX `item_id_UNIQUE` (`item_id` ASC) VISIBLE,
  INDEX `Cid_idx` (`category_Id` ASC) VISIBLE,
  INDEX `Fid_idx` (`firm_id` ASC) VISIBLE,
  CONSTRAINT `Cid`
    FOREIGN KEY (`category_Id`)
    REFERENCES `shop`.`category` (`category_Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ItFid`
    FOREIGN KEY (`firm_id`)
    REFERENCES `shop`.`price` (`firmId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
